### ISSUE TITLE
只有启动页

### ISSUE THREAD

**Issue by LionWY** [crazycodeboy/GitHubPopular#13]
只有启动页，没有后续了。。。。

**Comment by wangdetong** [comment]
I also encountered this problem,
before: use xcode run directly
now：First use terminal input "npm start"，then use xcode run，that is ok!

**Comment by ahz549467483** [comment]
请问你的问题解决了吗

**Comment by unhappy224** [comment]
不要用cnpm  更新npm后再install  可以用镜像
```shell
rm -rf node_modules 
sudo npm install -g npm 
npm install
```

**Comment by aliyoge** [comment]
@LionWY 遇到同样的问题，你解决了没有？

**Comment by LionWY** [comment]
没有，我之后换了开源项目看，https://github.com/ForkList/react-native-gitfeed.git 这个也不错

**Comment by BarryGuo** [comment]
react-native的版本改成.0.38.0就可以了

**Comment by gewuxy** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by laixi** [comment]
遇到同样的问题 有没有已经解决了的？

**Comment by 895802225** [comment]
我成功了，本来也是卡在启动页，我将react-native的版本改成.0.38.0，然后发现页面变到了popular主页，之后马上变红宕机，然后我就想着页面既然加载了，我又换回了之前的react-native版本，然后就好了
