### ISSUE TITLE
运行项目后报错，已经adb devices 确认了有设备在线。

### ISSUE THREAD

**Issue by apkcoder** [crazycodeboy/GitHubPopular#4]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command 'security''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 4.288 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by crazycodeboy** [comment]
用AndroidStudio打开GitHubPopular/android运行一下，确认是否连接到了设备

**Comment by hq001a** [comment]
issue3已经有人说了这个问题。
