### ISSUE TITLE
SyntaxError:Strict mode does not allow function declaration in a lexically nested statement.

### ISSUE THREAD

**Issue by NickTet** [crazycodeboy/GitHubPopular#53]
很好奇你们都没遇到这个问题吗？SyntaxError:Strict mode does not allow function declaration in a lexically nested statement.

**Comment by Likarl** [comment]
+1，不过在debug模式下可以正常运行。
https://github.com/facebook/react-native/issues/11389#issuecomment-265995961

**Comment by NickTet** [comment]
我把版本升级了 ，问题解决了

**Comment by zhenizhui** [comment]
@NickTet 请问升级到了哪个版本了? 😄

**Comment by zhenizhui** [comment]
```
"dependencies": {
        "react": "15.4.1",
        "react-native": "0.39.1"
}
```
使用这两个版本
