### ISSUE TITLE
failed to open, when i run this app on my android phone

### ISSUE THREAD

**Issue by allan2coder** [crazycodeboy/GitHubPopular#57]
![screenshot_20171204-142601_ b 1e292ed](https://user-images.githubusercontent.com/14307551/33539064-6d536540-d8ff-11e7-865c-f93a919bc323.jpg)

how to fix it?

**Comment by 18826243441m** [comment]
+1

**Comment by allan2coder** [comment]
@18826243441m  try to run this command: `chmod +x android/gradlew`.

**Comment by allan2coder** [comment]
I have solve this problem

**Comment by 18826243441m** [comment]
oh my god
not work

**Comment by allan2coder** [comment]
@crazycodeboy

**Comment by Shouheng88** [comment]
I got the same error

**Comment by frinda** [comment]
I got the same error too
