### ISSUE TITLE
iOS运行编译的时候报错

### ISSUE THREAD

**Issue by Feng999** [crazycodeboy/GitHubPopular#8]
您好，在执行react-native run-ios后，提示BUILD FAILED，具体信息如下：
`
./ReactNative/GitHubPopular/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: error: 
      ignoring return value of function declared with warn_unused_result
      attribute [-Werror,-Wunused-result]
  SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
  ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./ReactNative/GitHubPopular/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: error: 
      ignoring return value of function declared with warn_unused_result
      attribute [-Werror,-Wunused-result]
    SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);
    ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated._
`
求指教～

**Comment by crazycodeboy** [comment]
fix in #1

**Comment by Feng999** [comment]
在中文官网找到了[答案](http://reactnative.cn/post/2595):
将
`SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);`
改为
`(void)SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);`即可。
